### ISSUE TITLE
Anaconda now supports Python 3

### ISSUE THREAD

**Issue by rschwarz** [OpenTechSchool/python-data-intro#11]
The learning material has a section on installing IPython via Anaconda. Then there is some discussion about Python 2 and 3. Previously, Anaconda was only available for Python 2, but this is no longer the case. I think the material should then consistently use Python 3 throughout and skip this discussion.

**Comment by projectgus** [comment]
Hi Robert,

Thanks for mentioning this. I absolutely agree. The last time we looked into this, Python 3 was still an additional install option (using conda) on top of the Python 2 Anaconda. However I see on the downloads page for Anaconda 2.0.1 that you can now get a Python 3.4 complete installer image. Yay!

To avoid accidental errors someone probably still needs to run through all the steps with Anaconda 2.0.1/Python 3 to check that all the subtle differences are taken care of. But I think it's absolutely a good idea to transition.

Angus

**Comment by ghost** [comment]
We are in the process of updating the tutorials and removing references to python 2 (see issue [Remove references to Python 2](https://github.com/OpenTechSchool/python-data-intro/issues/16)). That should solve this issue.
