### ISSUE TITLE
python files vs. ipython files

### ISSUE THREAD

**Issue by SonOfLilit** [OpenTechSchool/python-data-intro#3]
Email from a workshop participant:

URL:
http://opentechschool.github.io/python-data-intro/core/notebook.html

Title - loading Python files:
I lost about 15 minutes realizing its PYTHON and not Ipython files I can load.. after talking only on Ipython, might be worth an emphasis.

**Comment by ghost** [comment]
I think this is less of an issue now that we refer pretty much exclusively to Jupyter Notebooks. IPython will play a smaller role in the new revisions.
